allow to customize readiness probe path and configure additional component ports
ytsaurus/yt-k8s-operator pull request #251
Opened 2024-04-22 14:41 UTC by kruftik

2024-04-24 11:04 UTC, l0kix2 requested changes

2024-04-24 11:04 UTC, l0kix2 commented on pkg/components/server.go
> +				Name:          consts.YTMonitoringContainerPortName,
Suppose we should mention this backward incompatibility rename in release notes after merge.

2024-04-25 15:43 UTC, kruftik commented
@l0kix2 I took all of your comments into account, could you take another look?

2024-04-25 15:45 UTC, kruftik commented on pkg/components/httpproxy.go
> +		WithCustomReadinessProbeEndpoint(ptr.T(intstr.FromInt32(consts.HTTPProxyHTTPPort)), ptr.T("/ping")),
Agree, except for the pointers since it are used for the obvious reason

2024-04-25 16:20 UTC, l0kix2 commented on pkg/components/httpproxy.go
> +		WithCustomReadinessProbeEndpoint(ptr.T(intstr.FromInt32(consts.HTTPProxyHTTPPort)), ptr.T("/ping")),
What are the reasons? They are not obvious to me it seems.

2024-04-25 16:39 UTC, kruftik commented on pkg/components/httpproxy.go
> +		WithCustomReadinessProbeEndpoint(ptr.T(intstr.FromInt32(consts.HTTPProxyHTTPPort)), ptr.T("/ping")),
> What are the reasons? They are not obvious to me it seems.

in order to differentiate case of provided port and/or path and not, to allow defaults overriding both simultaneously and only partly

2024-04-25 16:52 UTC, kruftik commented on pkg/components/httpproxy.go
> +		WithCustomReadinessProbeEndpoint(ptr.T(intstr.FromInt32(consts.HTTPProxyHTTPPort)), ptr.T("/ping")),
btw, refactored into two separate options and dropped the pointers away

2024-04-25 17:32 UTC, l0kix2 approved these changes
Looks good.

Do we expect some breaking changes in behaviour when we roll operator with this update?

2024-04-25 17:34 UTC, kruftik commented
> Looks good.
> 
> Do we expect some breaking changes in behaviour when we roll operator with this update?

nope. well, except for the fact that sts removal is required to changes get applied to pod manifests

2024-04-26 09:38 UTC, merged